services:
  ice-db:
    container_name: ice-db
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=ice
      - POSTGRES_USER=ice
      - POSTGRES_PASSWORD=icepassword
volumes:
  postgres_data: